'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CustomerEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CustomerEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property 客戶資料() As DbSet(Of 客戶資料)
    Public Overridable Property 客戶銀行資訊() As DbSet(Of 客戶銀行資訊)
    Public Overridable Property 客戶聯絡人() As DbSet(Of 客戶聯絡人)
    Public Overridable Property MyView() As DbSet(Of MyView)

End Class
