'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class 客戶聯絡人
    Public Property Id As Integer
    Public Property 客戶Id As Integer
    Public Property 職稱 As String
    Public Property 姓名 As String
    Public Property Email As String
    Public Property 手機 As String
    Public Property 電話 As String
    Public Property IsDelete As Boolean

    Public Overridable Property 客戶資料 As 客戶資料

End Class
