'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class 客戶銀行資訊
    Public Property Id As Integer
    Public Property 客戶Id As Integer
    Public Property 銀行名稱 As String
    Public Property 銀行代碼 As Integer
    Public Property 分行代碼 As Nullable(Of Integer)
    Public Property 帳戶名稱 As String
    Public Property 帳戶號碼 As String
    Public Property IsDelete As Boolean

    Public Overridable Property 客戶資料 As 客戶資料

End Class
